uploads = []
generated = []

[[outputs]]
id = "cVL5fn6aK5F7XusmogdXV"
uri = "file://frame_01.jpg"
type = "image"
title = "Frame 1 — 0:05"

[[outputs]]
id = "CurUxu1fhaROlohSsXkKI"
uri = "file://frame_02.jpg"
type = "image"
title = "Frame 2 — 0:10"

[[outputs]]
id = "BoSn84kjJvjg3di9ztkw5"
uri = "file://frame_03.jpg"
type = "image"
title = "Frame 3 — 0:15"

[[outputs]]
id = "EBfGCUDzW6kz5DyD7SJTu"
uri = "file://frame_04.jpg"
type = "image"
title = "Frame 4 — 0:20"

[[outputs]]
id = "u4X6MmlqDtgcXEVV8t9Qq"
uri = "file://frame_05.jpg"
type = "image"
title = "Frame 5 — 0:25"

[[outputs]]
id = "fqbsFdjnHPq6ZF-6bAmrD"
uri = "file://frame_06.jpg"
type = "image"
title = "Frame 6 — 0:30"

[[outputs]]
id = "mswpW3wBVj9JzGTyUDdtY"
uri = "file://frame_07.jpg"
type = "image"
title = "Frame 7 — 0:35"

[[outputs]]
id = "Y3I_2cgx0AV3_6-xpM1y9"
uri = "file://frame_08.jpg"
type = "image"
title = "Frame 8 — 0:40"

[[outputs]]
id = "FAOxDrrnCdFn6S8yQNk3g"
uri = "file://frame_09.jpg"
type = "image"
title = "Frame 9 — 0:44"

[[outputs]]
id = "xOPn2UfrnY0VjE4FZFaLo"
uri = "file://frame_b01.jpg"
type = "image"
title = "Frame — 0:02"

[[outputs]]
id = "bOGm1g0AGAsMmEZDtJ5Lf"
uri = "file://frame_b03.jpg"
type = "image"
title = "Frame — 0:07"

[[outputs]]
id = "YpixXzj-XmghupXxDs8R0"
uri = "file://frame_b06.jpg"
type = "image"
title = "Frame — 0:12"

[[outputs]]
id = "K_uQji2rvFFMDm6RMom1q"
uri = "file://frame_b08.jpg"
type = "image"
title = "Frame — 0:17"

[[outputs]]
id = "WkmAJrsIYJ1Ocuk9iKWmn"
uri = "file://frame_b11.jpg"
type = "image"
title = "Frame — 0:22"

[[outputs]]
id = "QlXgi7M8unZYFrb5dhAd7"
uri = "file://frame_b13.jpg"
type = "image"
title = "Frame — 0:27"

[[outputs]]
id = "q8Nr_agqDyAPXX7lX-zNO"
uri = "file://frame_b16.jpg"
type = "image"
title = "Frame — 0:32"

[[outputs]]
id = "tnXHv9jWrPG7y-VH2okEV"
uri = "file://frame_b18.jpg"
type = "image"
title = "Frame — 0:37"

[[outputs]]
id = "OblO8_oeyVltZv7cQ8aC9"
uri = "file://frame_b21.jpg"
type = "image"
title = "Frame — 0:42"

[[outputs]]
id = "beuNdayjjQr-1abU9cu6G"
uri = "file://frame_b22.jpg"
type = "image"
title = "Frame — 0:44"

[[outputs]]
id = "n_iYtoY2IXmnTcYXeLDmt"
uri = "file://frame_c34.jpg"
type = "image"
title = "0:34"

[[outputs]]
id = "DyKryMPkVN9uykNjfAim0"
uri = "file://frame_c35.jpg"
type = "image"
title = "0:35"

[[outputs]]
id = "ZIVwhXWgQRLypSQp-QDBW"
uri = "file://frame_c36.jpg"
type = "image"
title = "0:36"

[[outputs]]
id = "cmZwFQ4RYizptcp_kngfi"
uri = "file://frame_c37.jpg"
type = "image"
title = "0:37"

[[outputs]]
id = "nx-tWJDJl70tgzswNwamu"
uri = "file://frame_c38.jpg"
type = "image"
title = "0:38"

[[outputs]]
id = "_LvXfwOSJ26HmLetlvdEk"
uri = "file://frame_c39.jpg"
type = "image"
title = "0:39"

[[outputs]]
id = "GrYKde2NTfJTdS3yjFO4P"
uri = "file://frame_c40.jpg"
type = "image"
title = "0:40"
