// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/oto-button/Amber.tsx": () => import("../components/mockups/oto-button/Amber.tsx"),
  "./components/mockups/oto-button/Red.tsx": () => import("../components/mockups/oto-button/Red.tsx"),
  "./components/mockups/oto-button/SlateOutline.tsx": () => import("../components/mockups/oto-button/SlateOutline.tsx"),
  "./components/mockups/oto-button/WhiteBlack.tsx": () => import("../components/mockups/oto-button/WhiteBlack.tsx")
};
